parser: "@typescript-eslint/parser"
plugins:
    - react
    - prettier
    - react-hooks
    - jsx-a11y
    - import
    - "@typescript-eslint"

settings:
    import/resolver:
        typescript:

env:
    browser: true
    es2021: true

extends:
    - eslint:recommended
    - plugin:react/recommended
    - plugin:@typescript-eslint/recommended
    - plugin:jsx-a11y/recommended
    - plugin:import/errors
    - plugin:import/warnings
    - prettier

parserOptions:
    ecmaFeatures:
        jsx: true
    ecmaVersion: 12
    sourceType: module



rules:
    indent:
        - error
        - 4

    linebreak-style:
        - error
        - unix

    quotes:
        - error
        - single

    semi:
        - error
        - never
